version: '3.8'

services:
  redis-service:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis-service

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - redis-service